import { StyleSheet } from "react-native";

const COLORS = {
  bg: "#f6f5f1",
  bgWarm: "#ece9e2",
  card: "#ffffff",
  cardBorder: "#e7e5e4",
  teal: "#0d9488",
  tealDark: "#115e59",
  tealLight: "#ccfbf1",
  coral: "#ea580c",
  green: "#16a34a",
  greenLight: "#dcfce7",
  red: "#dc2626",
  redLight: "#fee2e2",
  amber: "#d97706",
  amberLight: "#fef3c7",
  blue: "#2563eb",
  blueLight: "#dbeafe",
  ink: "#1c1917",
  inkSecondary: "#44403c",
  inkMuted: "#78716c",
  inkFaint: "#a8a29e",
  border: "#e7e5e4",
  borderStrong: "#d6d3d1",
  inputBg: "#ffffff",
};

export { COLORS };

export default StyleSheet.create({
  screen: {
    flex: 1,
    padding: 20,
    backgroundColor: COLORS.bg,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    marginBottom: 4,
    color: COLORS.ink,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.inkMuted,
    marginBottom: 20,
    lineHeight: 20,
  },
  label: {
    fontSize: 12,
    fontWeight: "600",
    marginTop: 14,
    marginBottom: 5,
    color: COLORS.inkSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: COLORS.inputBg,
    padding: 13,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.borderStrong,
    color: COLORS.ink,
    fontSize: 15,
  },
  btn: {
    backgroundColor: COLORS.teal,
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 14,
  },
  btnSecondary: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
  },
  btnDanger: {
    backgroundColor: COLORS.red,
  },
  btnGreen: {
    backgroundColor: COLORS.green,
  },
  btnText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  btnTextSecondary: {
    color: COLORS.inkSecondary,
    fontWeight: "600",
    fontSize: 15,
  },
  card: {
    backgroundColor: COLORS.card,
    padding: 18,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  cardHeader: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.inkMuted,
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 8,
  },
  link: {
    color: COLORS.teal,
    marginTop: 18,
    textAlign: "center",
    fontWeight: "600",
    fontSize: 14,
  },
  muted: {
    color: COLORS.inkMuted,
    fontSize: 13,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 14,
  },
  statValue: {
    fontSize: 26,
    fontWeight: "700",
    color: COLORS.teal,
    letterSpacing: -0.5,
  },
  statLabel: {
    fontSize: 11,
    color: COLORS.inkMuted,
    fontWeight: "500",
    marginTop: 2,
  },
  infoChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
  },
  infoChipIcon: {
    width: 38,
    height: 38,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
});
