import { StyleSheet } from "react-native";

const COLORS = {
  bg: "#F7F8FC",
  bgWarm: "#FFFFFF",
  card: "#FFFFFF",
  cardBorder: "rgba(123, 44, 191, 0.05)",
  teal: "#00F5D4",
  tealDark: "#00C2A8",
  tealLight: "rgba(0, 245, 212, 0.15)",
  coral: "#FF5E00",
  green: "#10b981",
  greenLight: "rgba(16, 185, 129, 0.15)",
  red: "#FF5E00",
  redLight: "rgba(255, 94, 0, 0.1)",
  amber: "#FF7B00",
  amberLight: "rgba(255, 123, 0, 0.1)",
  blue: "#7B2CBF",
  blueLight: "rgba(123, 44, 191, 0.1)",
  violet: "#7B2CBF",
  lime: "#CCFF00",
  ink: "#1A1A2E",
  inkSecondary: "#5A5A72",
  inkMuted: "#8D8D9F",
  inkFaint: "#D3D3E0",
  border: "rgba(123, 44, 191, 0.08)",
  borderStrong: "rgba(123, 44, 191, 0.15)",
  inputBg: "#F4F5F9",
};

export { COLORS };

export default StyleSheet.create({
  screen: {
    flex: 1,
    padding: 24,
    backgroundColor: COLORS.bg,
  },
  title: {
    fontSize: 34,
    fontWeight: "800",
    marginBottom: 8,
    color: COLORS.ink,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.inkSecondary,
    marginBottom: 32,
    lineHeight: 24,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    marginTop: 20,
    marginBottom: 8,
    color: COLORS.inkSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: COLORS.inputBg,
    padding: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "transparent",
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: "500",
  },
  btn: {
    backgroundColor: COLORS.violet,
    padding: 20,
    borderRadius: 100,
    alignItems: "center",
    marginTop: 24,
    shadowColor: COLORS.violet,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  btnSecondary: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  btnDanger: {
    backgroundColor: COLORS.coral,
    shadowColor: COLORS.coral,
  },
  btnGreen: {
    backgroundColor: COLORS.lime, 
    shadowColor: COLORS.lime,
  },
  btnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  btnTextSecondary: {
    color: COLORS.ink,
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  card: {
    backgroundColor: COLORS.card,
    padding: 28,
    borderRadius: 32,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    shadowColor: COLORS.violet,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
    elevation: 4,
  },
  cardHeader: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.violet,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 16,
    backgroundColor: COLORS.blueLight,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 100,
    alignSelf: 'flex-start',
  },
  link: {
    color: COLORS.violet,
    marginTop: 24,
    textAlign: "center",
    fontWeight: "700",
    fontSize: 15,
  },
  muted: {
    color: COLORS.inkMuted,
    fontSize: 14,
    fontWeight: "500",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 100,
    backgroundColor: COLORS.bg,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 24,
  },
  statValue: {
    fontSize: 42,
    fontWeight: "800",
    color: COLORS.ink,
    letterSpacing: -1,
  },
  statLabel: {
    fontSize: 13,
    color: COLORS.inkSecondary,
    fontWeight: "700",
    marginTop: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: COLORS.violet,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  infoChipIcon: {
    width: 56,
    height: 56,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.blueLight,
  },
});
